export interface Question {
  text: string;
  topic: string;
  type: 'D' | 'I'; // D = Direta, I = Inversa
}

export const QUESTIONS: Question[] = [
  { topic: "Tópico 01 - Assédio de qualquer natureza no trabalho", text: "Você já presenciou ou sofreu comentários ofensivos, piadas ou insinuações inadequadas no ambiente de trabalho?", type: "D" },
  { topic: "Tópico 01 - Assédio de qualquer natureza no trabalho", text: "Você se sente à vontade para relatar situações de assédio moral ou sexual na empresa sem medo de represálias?", type: "I" },
  { topic: "Tópico 01 - Assédio de qualquer natureza no trabalho", text: "Existe um canal seguro e sigiloso para denunciar assédio na empresa?", type: "I" },
  { topic: "Tópico 01 - Assédio de qualquer natureza no trabalho", text: "Há casos conhecidos de assédio moral ou sexual que não foram devidamente investigados ou punidos?", type: "D" },
  { topic: "Tópico 01 - Assédio de qualquer natureza no trabalho", text: "O RH e os gestores demonstram comprometimento real com a prevenção do assédio?", type: "I" },
  { topic: "Tópico 02 - Falta de suporte/apoio no trabalho", text: "Você sente que pode contar com seus colegas em momentos de dificuldade?", type: "I" },
  { topic: "Tópico 02 - Falta de suporte/apoio no trabalho", text: "Existe apoio da liderança para lidar com desafios relacionados ao trabalho?", type: "I" },
  { topic: "Tópico 02 - Falta de suporte/apoio no trabalho", text: "O RH está presente e atuante quando surgem conflitos ou dificuldades no trabalho?", type: "I" },
  { topic: "Tópico 02 - Falta de suporte/apoio no trabalho", text: "Os gestores promovem um ambiente saudável e respeitoso?", type: "I" },
  { topic: "Tópico 02 - Falta de suporte/apoio no trabalho", text: "Você sente que pode expressar suas dificuldades no trabalho sem ser julgado(a)?", type: "I" },
  { topic: "Tópico 03 - Má gestão de mudanças organizacionais", text: "Mudanças organizacionais impactaram negativamente seu sentimento de segurança no trabalho?", type: "D" },
  { topic: "Tópico 03 - Má gestão de mudanças organizacionais", text: "Há comunicação clara sobre mudanças que afetam a empresa ou os trabalhadores?", type: "I" },
  { topic: "Tópico 03 - Má gestão de mudanças organizacionais", text: "Você já sentiu que seu emprego estava ameaçado sem explicações claras durante períodos de mudança?", type: "D" },
  { topic: "Tópico 03 - Má gestão de mudanças organizacionais", text: "Existe transparência na comunicação da empresa durante processos de mudança?", type: "I" },
  { topic: "Tópico 04 - Baixa clareza de papel/função", text: "Você recebe instruções claras sobre suas responsabilidades no trabalho?", type: "I" },
  { topic: "Tópico 04 - Baixa clareza de papel/função", text: "A comunicação da empresa ajuda você a entender o que é esperado do seu trabalho?", type: "I" },
  { topic: "Tópico 04 - Baixa clareza de papel/função", text: "A comunicação entre equipes e setores contribui para a clareza das suas tarefas?", type: "I" },
  { topic: "Tópico 04 - Baixa clareza de papel/função", text: "Você se sente confortável para pedir esclarecimentos quando não entende suas funções?", type: "I" },
  { topic: "Tópico 05 - Baixas recompensas e reconhecimento", text: "Você sente que seu esforço e desempenho são reconhecidos pela liderança?", type: "I" },
  { topic: "Tópico 05 - Baixas recompensas e reconhecimento", text: "Você recebe feedback construtivo sobre o seu trabalho com regularidade?", type: "I" },
  { topic: "Tópico 05 - Baixas recompensas e reconhecimento", text: "Você já se sentiu desmotivado(a) por falta de reconhecimento no trabalho?", type: "D" },
  { topic: "Tópico 06 - Baixo controle no trabalho / Falta de autonomia", text: "Você tem liberdade para tomar decisões sobre como executar suas tarefas diárias?", type: "I" },
  { topic: "Tópico 06 - Baixo controle no trabalho / Falta de autonomia", text: "A empresa confia na sua capacidade de organizar e gerenciar o próprio trabalho?", type: "I" },
  { topic: "Tópico 06 - Baixo controle no trabalho / Falta de autonomia", text: "O excesso de controle ou burocracia interfere no seu desempenho?", type: "D" },
  { topic: "Tópico 06 - Baixo controle no trabalho / Falta de autonomia", text: "Existe excesso de supervisão que impacte negativamente sua produtividade ou bem-estar?", type: "D" },
  { topic: "Tópico 07 - Baixa justiça organizacional", text: "Você acha justas e claras as formas que a empresa usa para avaliar o seu trabalho?", type: "I" },
  { topic: "Tópico 07 - Baixa justiça organizacional", text: "Você sente que há igualdade no reconhecimento entre diferentes áreas ou equipes?", type: "I" },
  { topic: "Tópico 07 - Baixa justiça organizacional", text: "Você sente que há transparência nas decisões de desligamento na empresa?", type: "I" },
  { topic: "Tópico 07 - Baixa justiça organizacional", text: "Você já presenciou casos de demissões injustas?", type: "D" },
  { topic: "Tópico 08 - Eventos violentos ou traumáticos", text: "Você já vivenciou ou presenciou alguma situação de violência grave no trabalho?", type: "D" },
  { topic: "Tópico 08 - Eventos violentos ou traumáticos", text: "Você já passou por algum evento grave no trabalho (acidente sério, situação de risco extremo)?", type: "D" },
  { topic: "Tópico 08 - Eventos violentos ou traumáticos", text: "Alguma situação vivida no trabalho já foi tão marcante que deixou medo, choque ou forte abalo emocional?", type: "D" },
  { topic: "Tópico 09 - Baixa demanda no trabalho (Subcarga)", text: "Você sente que, na maior parte do tempo, tem pouco trabalho a realizar durante sua jornada?", type: "D" },
  { topic: "Tópico 09 - Baixa demanda no trabalho (Subcarga)", text: "Você costuma ficar com tempo ocioso no trabalho por falta de tarefas ou demandas claras?", type: "D" },
  { topic: "Tópico 09 - Baixa demanda no trabalho (Subcarga)", text: "Você sente que suas habilidades ou conhecimentos são pouco utilizados no seu trabalho?", type: "D" },
  { topic: "Tópico 09 - Baixa demanda no trabalho (Subcarga)", text: "Seu trabalho costuma ser pouco desafiador ou repetitivo a ponto de gerar desânimo?", type: "D" },
  { topic: "Tópico 10 - Excesso de demandas no trabalho (Sobrecarga)", text: "Você sente que sua carga de trabalho diária é maior do que consegue realizar dentro do horário normal?", type: "D" },
  { topic: "Tópico 10 - Excesso de demandas no trabalho (Sobrecarga)", text: "Você frequentemente precisa fazer horas extras ou levar trabalho para casa?", type: "D" },
  { topic: "Tópico 10 - Excesso de demandas no trabalho (Sobrecarga)", text: "Você já teve sintomas físicos ou emocionais (exaustão, ansiedade, insônia) devido ao excesso de trabalho?", type: "D" },
  { topic: "Tópico 10 - Excesso de demandas no trabalho (Sobrecarga)", text: "A equipe é dimensionada corretamente para a demanda de trabalho existente?", type: "I" },
  { topic: "Tópico 11 - Maus relacionamentos no local de trabalho", text: "Você já evitou colegas ou superiores por causa de desentendimentos frequentes?", type: "D" },
  { topic: "Tópico 11 - Maus relacionamentos no local de trabalho", text: "Você percebe rivalidade excessiva ou desnecessária entre colegas ou setores?", type: "D" },
  { topic: "Tópico 11 - Maus relacionamentos no local de trabalho", text: "Conflitos no trabalho costumam ser resolvidos de forma justa?", type: "I" },
  { topic: "Tópico 12 - Trabalho em condições de difícil comunicação", text: "Você trabalha em condições (turnos diferentes, trabalho externo) que dificultam a comunicação?", type: "D" },
  { topic: "Tópico 12 - Trabalho em condições de difícil comunicação", text: "A distância física entre você e sua equipe ou liderança dificulta a troca de informações?", type: "D" },
  { topic: "Tópico 12 - Trabalho em condições de difícil comunicação", text: "Você já teve dificuldade para receber informações importantes no momento certo?", type: "D" },
  { topic: "Tópico 12 - Trabalho em condições de difícil comunicação", text: "Você tem acesso fácil aos meios necessários para se comunicar com colegas e liderança?", type: "I" },
  { topic: "Tópico 13 - Trabalho remoto e isolado", text: "Você trabalha grande parte do tempo de forma remota ou sozinho(a), com pouco contato presencial?", type: "D" },
  { topic: "Tópico 13 - Trabalho remoto e isolado", text: "Você sente que o trabalho remoto ou isolado faz com que se sinta distante da equipe ou da empresa?", type: "D" },
  { topic: "Tópico 13 - Trabalho remoto e isolado", text: "Se trabalha de forma remota ou isolada, você sente que recebe apoio e acompanhamento adequados?", type: "I" }
];
